### ISSUE TITLE
support multiple compilation databases

### ISSUE THREAD

**Issue by 2bndy5** [cpp-linter/cpp-linter-rs#379]
A compilation database is relative to the compilation target. If users want to run cpp-linter on multiple targets, then the feedback is non-exhaustive.

cpp-linter's feedback (`thread-comment`, `step-summary`, and PR reviews) is not associated to a commit's SHA by cpp-linter's feedback dismissal/update behavior. So, running cpp-linter multiple times (from 1 commit) for different compilation targets would only show feedback for 1 target.

I'm not sure what the desirable solution for this would be, but it will not be a simple patch. In theory, I think the `database` option should accept a single string (as it does currently) or a mapping of paths to certain C/C++ sources.
```yaml
- uses: cpp-linter/cpp-linter-action@v2
  with:
    # use database in examples_pico/build for files in examples_pico
    # use database in build for all other files
    database: >-
      examples_pico/*.{cpp,h} : examples_pico/build |
      ./**.{c,cpp,h,hpp} : build
```

**Comment by 2bndy5** [comment]
I have been working on a different action that is designed to compile Arduino C++ for multiple targets. The compiling and reporting results are done in a separate actions. For example:

```yml
jobs:
  compile:
    strategy:
      matrix:
        target: [arduino-uno, rpi-pico]
    steps:
      - uses: arduino/compile-sketches@v1
        with:
          # this action leaves behind json artifacts in this path
          sketch-reports: compilation-reports
      # now upload artifacts for later processing
      - uses: actions/upload-artifacts@v6
        with:
          name: reports-${{ matrix.target }}
          path: compilation-reports/**

  report:
    needs: [compile]
    steps:
      # now download all compilation reports
      - uses: actions/download-artifacts@v6
        with:
          pattern: reports-*
          path: compilation-reports
      # use this action to post a comment based on all reports
      - uses: 2bndy5/arduino-report-size-deltas@v1
        with:
          sketch-reports: compilation-reports
```

Now I'm not sure cpp-linter needs to be broken up into separate actions to achieve support for multiple compilation targets. But, I do think that posting comments, annotations, step summary, and PR reviews can be toggled by a couple new input options:

1. Let `report-path` be the new input option to save report results to a path.
2. Let `no-report` be the input option to toggle feedback.

- if `report-path` is not empty and `no-report` is true, then just save machine-readable json artifacts in the given path.
- if `report-path` is not empty and `no-report` is false, then use machine-readable json artifacts in the given path to post comments and stuff.

Of course, this idea requires a convention for machine-readable artifacts that can be used accross multiple OSs and different compilation targets. There will have to be some de-duplication when reading from multiple json artifacts.
